github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/graalvm"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(17\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    17
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(21\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    21
- name:            JDK 24
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(24\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    24
- name:            JDK 25
  id:              jdk
  version_pattern: "25\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "25\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(25\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    25
- name:            Native Image 17
  id:              native-image-svm
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(17\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    17
- name:            Native Image 21
  id:              native-image-svm
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(21\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    21
- name:            Native Image 24
  id:              native-image-svm
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(24\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    24
- name:            Native Image 25
  id:              native-image-svm
  version_pattern: "25\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "25\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-x64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(25\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    25

# ARM64
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(17\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    17
    arch:       arm64
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(21\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    21
    arch:       arm64
- name:            JDK 24 ARM64
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(24\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    24
    arch:       arm64
- name:            JDK 25 ARM64
  id:              jdk
  version_pattern: "25\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "25\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(25\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    25
    arch:       arm64
- name:            Native Image 17 ARM64
  id:              native-image-svm
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(17\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    17
    arch:       arm64
- name:            Native Image 21 ARM64
  id:              native-image-svm
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(21\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    21
    arch:       arm64
- name:            Native Image 24 ARM64
  id:              native-image-svm
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(24\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    24
    arch:       arm64
- name:            Native Image 25 ARM64
  id:              native-image-svm
  version_pattern: "25\\.[\\d]+\\.[\\d]+"
  purl_pattern:    "25\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       graalvm-community-jdk-.*_linux-aarch64_bin.tar.gz
    owner:      graalvm
    repository: graalvm-ce-builds
    tag_filter: "^jdk-(25\\.[\\d]+\\.[\\d])$"
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    version:    25
    arch:       arm64
